import 'math_question.dart';

const divisorMultipleQuestions = <MathQuestion>[
  MathQuestion(
    prompt: '12의 약수가 아닌 것은 무엇일까요?',
    options: ['2', '3', '5', '6'],
    correctIndex: 2,
    hints: ['12를 나누어떨어지게 하는 수를 찾아봐요.', '12 ÷ 5의 나머지를 확인해 봐요.'],
    explanation: '12는 5로 나누어떨어지지 않으므로 5는 12의 약수가 아니에요.',
  ),
  MathQuestion(
    prompt: '18의 약수는 모두 몇 개일까요?',
    options: ['4개', '5개', '6개', '7개'],
    correctIndex: 2,
    hints: ['곱해서 18이 되는 수의 짝을 찾아봐요.', '1×18, 2×9, 3×6을 떠올려 봐요.'],
    explanation: '18의 약수는 1, 2, 3, 6, 9, 18로 모두 6개예요.',
  ),
  MathQuestion(
    prompt: '다음 중 7의 배수는 무엇일까요?',
    options: ['24', '28', '32', '36'],
    correctIndex: 1,
    hints: ['7을 여러 번 더해 봐요.', '7×4를 계산해 봐요.'],
    explanation: '7×4=28이므로 28은 7의 배수예요.',
  ),
  MathQuestion(
    prompt: '8과 12의 최대공약수는 무엇일까요?',
    options: ['2', '4', '6', '8'],
    correctIndex: 1,
    hints: ['두 수의 약수를 각각 적어 봐요.', '두 수에 공통인 약수 중 가장 큰 수를 찾아봐요.'],
    explanation: '공약수는 1, 2, 4이고 가장 큰 수는 4예요.',
  ),
  MathQuestion(
    prompt: '4와 6의 최소공배수는 무엇일까요?',
    options: ['8', '10', '12', '24'],
    correctIndex: 2,
    hints: ['4의 배수와 6의 배수를 차례로 적어 봐요.', '두 목록에서 처음으로 같은 수를 찾아봐요.'],
    explanation: '4의 배수와 6의 배수에서 처음 만나는 수는 12예요.',
  ),
  MathQuestion(
    prompt: '24의 약수는 무엇일까요?',
    options: ['5', '6', '7', '9'],
    correctIndex: 1,
    hints: ['24를 각 보기의 수로 나누어 봐요.', '24÷6은 나머지가 있을까요?'],
    explanation: '24÷6=4로 나누어떨어지므로 6은 24의 약수예요.',
  ),
  MathQuestion(
    prompt: '9의 다섯 번째 배수는 무엇일까요?',
    options: ['36', '40', '45', '54'],
    correctIndex: 2,
    hints: ['9를 다섯 번 더해 봐요.', '9×5를 계산해 봐요.'],
    explanation: '9×5=45이므로 다섯 번째 배수는 45예요.',
  ),
  MathQuestion(
    prompt: '15와 25의 최대공약수는 무엇일까요?',
    options: ['3', '5', '10', '15'],
    correctIndex: 1,
    hints: ['15와 25를 모두 나눌 수 있는 수를 찾아봐요.', '두 수 모두 5로 나누어져요.'],
    explanation: '15와 25의 공약수는 1, 5이고 최대공약수는 5예요.',
  ),
  MathQuestion(
    prompt: '3과 8의 최소공배수는 무엇일까요?',
    options: ['11', '16', '21', '24'],
    correctIndex: 3,
    hints: ['3의 배수 중 8로도 나누어지는 수를 찾아봐요.', '3×8을 생각해 봐요.'],
    explanation: '3과 8은 공약수가 1뿐이라 최소공배수는 3×8=24예요.',
  ),
  MathQuestion(
    prompt: '어떤 수의 약수에는 반드시 포함되는 두 수는?',
    options: ['0과 1', '1과 자기 자신', '2와 3', '5와 10'],
    correctIndex: 1,
    hints: ['모든 자연수는 1로 나누어져요.', '자기 자신으로 나누면 몫은 1이에요.'],
    explanation: '모든 자연수의 약수에는 1과 자기 자신이 반드시 포함돼요.',
  ),
  MathQuestion(
    prompt: '6의 배수이면서 9의 배수인 수는?',
    options: ['12', '18', '27', '30'],
    correctIndex: 1,
    hints: ['각 보기를 6과 9로 나누어 봐요.', '6×3과 9×2는 같은 수예요.'],
    explanation: '18은 6×3이면서 9×2이므로 두 수의 공배수예요.',
  ),
  MathQuestion(
    prompt: '20과 30의 공약수가 아닌 것은?',
    options: ['1', '2', '5', '6'],
    correctIndex: 3,
    hints: ['각 수가 20과 30을 모두 나누는지 확인해요.', '20은 6으로 나누어떨어지지 않아요.'],
    explanation: '6은 20의 약수가 아니므로 두 수의 공약수가 아니에요.',
  ),
  MathQuestion(
    prompt: '두 수의 최대공약수가 3일 때 공약수가 될 수 없는 수는?',
    options: ['1', '3', '6', '모두 가능'],
    correctIndex: 2,
    hints: ['공약수는 최대공약수의 약수예요.', '3의 약수는 1과 3뿐이에요.'],
    explanation: '공약수는 1과 3만 가능하므로 6은 공약수가 될 수 없어요.',
  ),
  MathQuestion(
    prompt: '5와 10의 최소공배수는 무엇일까요?',
    options: ['5', '10', '15', '50'],
    correctIndex: 1,
    hints: ['10은 5의 배수인지 생각해 봐요.', '두 수의 배수 중 가장 작은 수를 골라요.'],
    explanation: '10은 5의 배수이면서 10의 첫 번째 배수이므로 답은 10이에요.',
  ),
  MathQuestion(
    prompt: '36을 나누어떨어지게 하는 수는?',
    options: ['7', '8', '9', '10'],
    correctIndex: 2,
    hints: ['36을 각 보기로 나누어 봐요.', '9×4를 떠올려 봐요.'],
    explanation: '36=9×4이므로 9는 36의 약수예요.',
  ),
];
